language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: bosofelipe-github
    token:
      secure: 9fa95782aea30931b84cd302b7bafa9331a810d0
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


#language: java
#jdk:
#- oraclejdk8
# git strips the wrapper jar file so we have to force its download during the build
#install:
#- mvn -N io.takari:maven:wrapper
#- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
