package com.luckybox.bet.rule;

public enum RuleType {

	PRIME_LOW, PRIME_HIGH, PAIR_HIGH, FIBONACCI_HIGH, FIRST_LINE, SECOND_LINE, THIRD_LINE, FOURTH_LINE, FIVETH_LINE, SUM_LOW, SUM_HIGH, LAST_RAFFLE_HIGH, LAST_RAFFLE_LOW, CURRENT_SEQUENCE, ALREADY_DRAWN, FIBONACCI_LOW, PAIR_LOW
}
