package com.luckybox.bet.rule;

public enum RuleType {

	PRIME_LOW,// 
	PRIME_HIGH,//
	PAIR_HIGH,//
	PAIR_LOW,//
	FIBONACCI_HIGH,//
	FIBONACCI_LOW,//
	SUM_LOW,//
	SUM_HIGH,//
	LAST_RAFFLE_HIGH,// 
	LAST_RAFFLE_LOW,//
	CURRENT_SEQUENCE,//
	ALREADY_DRAWN,//
	QTD_SEQUENCE_HIGH,// 
	QTD_SEQUENCE_LOW,//
	GREATER_SEQUENCE_HIGH,//
	GREATER_SEQUENCE_LOW,//
	FIRST_LINE,//
	SECOND_LINE,//
	THIRD_LINE,//
	FOURTH_LINE, //
	FIVETH_LINE//
	
}
